

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class User : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the User entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public User()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public User(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.User> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.User.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void User_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void User_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Login
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Login);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Login, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Login_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Login_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Login_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Password
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Password);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Password, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Email
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Email);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Email, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PhotoUrl
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.PhotoUrl);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.PhotoUrl, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhotoUrl_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhotoUrl_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhotoUrl_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Group Group
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Group);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Group, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Group_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Group_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Group_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.UserConfigurationItem> UserConfigurationItems
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserConfigurationItems);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.UserConfigurationItem> UserConfigurationItemsQuery
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetQuery(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserConfigurationItems);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.User,
                global::LightSwitchApplication.User.DetailsClass,
                global::LightSwitchApplication.User.DetailsClass.IImplementation,
                global::LightSwitchApplication.User.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>.Entry
                __UserEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>.Entry(
                    global::LightSwitchApplication.User.DetailsClass.__User_CreateNew,
                    global::LightSwitchApplication.User.DetailsClass.__User_Created,
                    global::LightSwitchApplication.User.DetailsClass.__User_AllowSaveWithErrors);
            private static global::LightSwitchApplication.User __User_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.User> es)
            {
                return new global::LightSwitchApplication.User(es);
            }
            private static void __User_Created(global::LightSwitchApplication.User e)
            {
                e.User_Created();
            }
            private static bool __User_AllowSaveWithErrors(global::LightSwitchApplication.User e)
            {
                bool result = false;
                e.User_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.User.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> Login
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Login) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> Password
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Password) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> Email
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Email) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> PhotoUrl
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.PhotoUrl) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Group> Group
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Group) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Group>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.UserConfigurationItem> UserConfigurationItems
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserConfigurationItems) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.UserConfigurationItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new string Login { get; set; }
                new string Password { get; set; }
                new string Email { get; set; }
                new string PhotoUrl { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Group { get; set; }
                new global::System.Collections.IEnumerable UserConfigurationItems { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    Login = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "Login",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Login_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Login_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Login_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Login_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Login_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Login_OnValueChanged);
                private static void _Login_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Login, sf);
                }
                private static bool _Login_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.Login_IsReadOnly(ref result);
                    return result;
                }
                private static void _Login_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Login_Validate(r);
                }
                private static string _Login_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Login;
                }
                private static void _Login_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Login = v;
                }
                private static void _Login_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.Login_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    Password = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "Password",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Password_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Password_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Password_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Password_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Password_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Password_OnValueChanged);
                private static void _Password_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Password, sf);
                }
                private static bool _Password_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.Password_IsReadOnly(ref result);
                    return result;
                }
                private static void _Password_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Password_Validate(r);
                }
                private static string _Password_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Password;
                }
                private static void _Password_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Password = v;
                }
                private static void _Password_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.Password_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    Email = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "Email",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Email_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Email_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Email_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Email_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Email_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Email_OnValueChanged);
                private static void _Email_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Email, sf);
                }
                private static bool _Email_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.Email_IsReadOnly(ref result);
                    return result;
                }
                private static void _Email_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Email_Validate(r);
                }
                private static string _Email_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Email;
                }
                private static void _Email_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Email = v;
                }
                private static void _Email_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.Email_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    PhotoUrl = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "PhotoUrl",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._PhotoUrl_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._PhotoUrl_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._PhotoUrl_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._PhotoUrl_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._PhotoUrl_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._PhotoUrl_OnValueChanged);
                private static void _PhotoUrl_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._PhotoUrl, sf);
                }
                private static bool _PhotoUrl_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.PhotoUrl_IsReadOnly(ref result);
                    return result;
                }
                private static void _PhotoUrl_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PhotoUrl_Validate(r);
                }
                private static string _PhotoUrl_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.PhotoUrl;
                }
                private static void _PhotoUrl_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PhotoUrl = v;
                }
                private static void _PhotoUrl_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.PhotoUrl_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Group>.Entry
                    Group = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Group>.Entry(
                        "Group",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Group_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Group_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Group_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Group_GetCoreImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Group_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Group_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Group_Refresh,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Group_OnValueChanged);
                private static void _Group_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Group>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Group, sf);
                }
                private static bool _Group_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.Group_IsReadOnly(ref result);
                    return result;
                }
                private static void _Group_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Group_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Group_GetCoreImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Group;
                }
                private static global::LightSwitchApplication.Group _Group_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Group, global::LightSwitchApplication.Group.DetailsClass>(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Group, ref d._Group);
                }
                private static void _Group_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, global::LightSwitchApplication.Group v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Group, ref d._Group, (i, ev) => i.Group = ev, v);
                }
                private static void _Group_Refresh(global::LightSwitchApplication.User.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Group, ref d._Group);
                }
                private static void _Group_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.Group_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.UserConfigurationItem>.Entry
                    UserConfigurationItems = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.UserConfigurationItem>.Entry(
                        "UserConfigurationItems",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserConfigurationItems_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserConfigurationItems_GetReferencedEntities,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserConfigurationItems_GetEntityCollection);
                private static void _UserConfigurationItems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.UserConfigurationItem>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._UserConfigurationItems, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.UserConfigurationItem> _UserConfigurationItems_GetReferencedEntities(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass>(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserConfigurationItems, ref d._UserConfigurationItems);
                }
                private static global::System.Collections.IEnumerable _UserConfigurationItems_GetEntityCollection(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.UserConfigurationItems;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _Login;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _Password;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _Email;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _PhotoUrl;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Group>.Data _Group;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.UserConfigurationItem>.Data _UserConfigurationItems;
            
        }
    
        #endregion
    }
    
    #endregion
}
