

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class UserConfigurationItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the UserConfigurationItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UserConfigurationItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UserConfigurationItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserConfigurationItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.UserConfigurationItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserConfigurationItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserConfigurationItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.UserConfigurationItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Key
        {
            get
            {
                return global::LightSwitchApplication.UserConfigurationItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.Key);
            }
            set
            {
                global::LightSwitchApplication.UserConfigurationItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.Key, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Key_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Key_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Key_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Value
        {
            get
            {
                return global::LightSwitchApplication.UserConfigurationItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.Value);
            }
            set
            {
                global::LightSwitchApplication.UserConfigurationItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.Value, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Value_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Value_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Value_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.User User
        {
            get
            {
                return global::LightSwitchApplication.UserConfigurationItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.User);
            }
            set
            {
                global::LightSwitchApplication.UserConfigurationItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.User, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void User_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void User_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void User_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.UserConfigurationItem,
                global::LightSwitchApplication.UserConfigurationItem.DetailsClass,
                global::LightSwitchApplication.UserConfigurationItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass>.Entry
                __UserConfigurationItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.UserConfigurationItem.DetailsClass.__UserConfigurationItem_CreateNew,
                    global::LightSwitchApplication.UserConfigurationItem.DetailsClass.__UserConfigurationItem_Created,
                    global::LightSwitchApplication.UserConfigurationItem.DetailsClass.__UserConfigurationItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.UserConfigurationItem __UserConfigurationItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserConfigurationItem> es)
            {
                return new global::LightSwitchApplication.UserConfigurationItem(es);
            }
            private static void __UserConfigurationItem_Created(global::LightSwitchApplication.UserConfigurationItem e)
            {
                e.UserConfigurationItem_Created();
            }
            private static bool __UserConfigurationItem_AllowSaveWithErrors(global::LightSwitchApplication.UserConfigurationItem e)
            {
                bool result = false;
                e.UserConfigurationItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string> Key
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.Key) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string> Value
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.Value) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::LightSwitchApplication.User> User
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.User) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::LightSwitchApplication.User>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Key { get; set; }
                new string Value { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation User { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.UserConfigurationItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.UserConfigurationItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.UserConfigurationItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.UserConfigurationItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.UserConfigurationItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>.Entry
                    Key = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>.Entry(
                        "Key",
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Key_Stub,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Key_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Key_Validate,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Key_GetImplementationValue,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Key_SetImplementationValue,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Key_OnValueChanged);
                private static void _Key_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserConfigurationItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Key, sf);
                }
                private static bool _Key_ComputeIsReadOnly(global::LightSwitchApplication.UserConfigurationItem e)
                {
                    bool result = false;
                    e.Key_IsReadOnly(ref result);
                    return result;
                }
                private static void _Key_Validate(global::LightSwitchApplication.UserConfigurationItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Key_Validate(r);
                }
                private static string _Key_GetImplementationValue(global::LightSwitchApplication.UserConfigurationItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Key;
                }
                private static void _Key_SetImplementationValue(global::LightSwitchApplication.UserConfigurationItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Key = v;
                }
                private static void _Key_OnValueChanged(global::LightSwitchApplication.UserConfigurationItem e)
                {
                    e.Key_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>.Entry
                    Value = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>.Entry(
                        "Value",
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Value_Stub,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Value_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Value_Validate,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Value_GetImplementationValue,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Value_SetImplementationValue,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._Value_OnValueChanged);
                private static void _Value_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserConfigurationItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Value, sf);
                }
                private static bool _Value_ComputeIsReadOnly(global::LightSwitchApplication.UserConfigurationItem e)
                {
                    bool result = false;
                    e.Value_IsReadOnly(ref result);
                    return result;
                }
                private static void _Value_Validate(global::LightSwitchApplication.UserConfigurationItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Value_Validate(r);
                }
                private static string _Value_GetImplementationValue(global::LightSwitchApplication.UserConfigurationItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Value;
                }
                private static void _Value_SetImplementationValue(global::LightSwitchApplication.UserConfigurationItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Value = v;
                }
                private static void _Value_OnValueChanged(global::LightSwitchApplication.UserConfigurationItem e)
                {
                    e.Value_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::LightSwitchApplication.User>.Entry
                    User = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::LightSwitchApplication.User>.Entry(
                        "User",
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._User_Stub,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._User_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._User_Validate,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._User_GetCoreImplementationValue,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._User_GetImplementationValue,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._User_SetImplementationValue,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._User_Refresh,
                        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties._User_OnValueChanged);
                private static void _User_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::LightSwitchApplication.User>.Data> c, global::LightSwitchApplication.UserConfigurationItem.DetailsClass d, object sf)
                {
                    c(d, ref d._User, sf);
                }
                private static bool _User_ComputeIsReadOnly(global::LightSwitchApplication.UserConfigurationItem e)
                {
                    bool result = false;
                    e.User_IsReadOnly(ref result);
                    return result;
                }
                private static void _User_Validate(global::LightSwitchApplication.UserConfigurationItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.User_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _User_GetCoreImplementationValue(global::LightSwitchApplication.UserConfigurationItem.DetailsClass d)
                {
                    return d.ImplementationEntity.User;
                }
                private static global::LightSwitchApplication.User _User_GetImplementationValue(global::LightSwitchApplication.UserConfigurationItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>(global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.User, ref d._User);
                }
                private static void _User_SetImplementationValue(global::LightSwitchApplication.UserConfigurationItem.DetailsClass d, global::LightSwitchApplication.User v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.User, ref d._User, (i, ev) => i.User = ev, v);
                }
                private static void _User_Refresh(global::LightSwitchApplication.UserConfigurationItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.UserConfigurationItem.DetailsClass.PropertySetProperties.User, ref d._User);
                }
                private static void _User_OnValueChanged(global::LightSwitchApplication.UserConfigurationItem e)
                {
                    e.User_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>.Data _Key;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, string>.Data _Value;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.UserConfigurationItem, global::LightSwitchApplication.UserConfigurationItem.DetailsClass, global::LightSwitchApplication.User>.Data _User;
            
        }
    
        #endregion
    }
    
    #endregion
}
