//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Aircraft
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Aircraft :
        global::LightSwitchApplication.Aircraft.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnManufacturerChanged()
        {
            this.___OnPropertyChanged("Manufacturer");
        }
        
        partial void OnModelChanged()
        {
            this.___OnPropertyChanged("Model");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Aircraft.DetailsClass.IImplementation.Orders
        {
            get
            {
                return this.Orders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> __Orders
        {
            get
            {
                if (this.___Orders == null)
                {
                    this.___Orders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "Orders",
                        () => this._Orders,
                        e => global::System.Object.Equals(e.AircraftId, this.Id));
                }
                return this.___Orders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> ___Orders;
        
    }
    #endregion
    
    #region Airport
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Airport :
        global::LightSwitchApplication.Airport.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnCityChanged()
        {
            this.___OnPropertyChanged("City");
        }
        
        partial void OnCountryIdChanged()
        {
            this.___OnPropertyChanged("CountryId");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Airport.DetailsClass.IImplementation.Orders
        {
            get
            {
                return this.Orders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> __Orders
        {
            get
            {
                if (this.___Orders == null)
                {
                    this.___Orders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "Orders",
                        () => this._Orders,
                        e => global::System.Object.Equals(e.LandingAirportId, this.Id));
                }
                return this.___Orders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> ___Orders;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Airport.DetailsClass.IImplementation.Orders1
        {
            get
            {
                return this.Orders1;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> __Orders1
        {
            get
            {
                if (this.___Orders1 == null)
                {
                    this.___Orders1 = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "Orders1",
                        () => this._Orders1,
                        e => global::System.Object.Equals(e.TakeoffAirportId, this.Id));
                }
                return this.___Orders1;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> ___Orders1;
        
    }
    #endregion
    
    #region Contract
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Contract :
        global::LightSwitchApplication.Contract.DetailsClass.IImplementation
    {
        partial void OnInstanceIdChanged()
        {
            this.___OnPropertyChanged("InstanceId");
            this.___OnPropertyChanged("Instance");
        }
        
        partial void OnTraderOneIdChanged()
        {
            this.___OnPropertyChanged("TraderOneId");
            this.___OnPropertyChanged("TraderOne");
        }
        
        partial void OnTraderTwoIdChanged()
        {
            this.___OnPropertyChanged("TraderTwoId");
            this.___OnPropertyChanged("TraderTwo");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreateDateChanged()
        {
            this.___OnPropertyChanged("CreateDate");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnStartDateChanged()
        {
            this.___OnPropertyChanged("StartDate");
        }
        
        partial void OnEndDateChanged()
        {
            this.___OnPropertyChanged("EndDate");
        }
        
        partial void OnTraderOneApprovalDateChanged()
        {
            this.___OnPropertyChanged("TraderOneApprovalDate");
        }
        
        partial void OnTraderTwoApprovalDateChanged()
        {
            this.___OnPropertyChanged("TraderTwoApprovalDate");
        }
        
        partial void OnIsTraderOneApprovedChanged()
        {
            this.___OnPropertyChanged("IsTraderOneApproved");
        }
        
        partial void OnIsTraderTwoApprovedChanged()
        {
            this.___OnPropertyChanged("IsTraderTwoApproved");
        }
        
        partial void OnBillingCurrencyIdChanged()
        {
            this.___OnPropertyChanged("BillingCurrencyId");
        }
        
        partial void OnTimeZoneIdChanged()
        {
            this.___OnPropertyChanged("TimeZoneId");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Contract.DetailsClass.IImplementation.Instance
        {
            get
            {
                return this.Instance;
            }
            set
            {
                this.Instance = (global::LightSwitchApplication.Implementation.Instance)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Instance> __Instance
        {
            get
            {
                if (this.___Instance == null)
                {
                    this.___Instance = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Instance>(
                        this,
                        "Instance",
                        new string[] { "InstanceId" },
                        e => global::System.Object.Equals(e.Id, this.InstanceId),
                        () => this._Instance,
                        e => this._Instance = e);
                }
                return this.___Instance;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Instance> ___Instance;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Contract.DetailsClass.IImplementation.TraderOne
        {
            get
            {
                return this.TraderOne;
            }
            set
            {
                this.TraderOne = (global::LightSwitchApplication.Implementation.Trader)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> __TraderOne
        {
            get
            {
                if (this.___TraderOne == null)
                {
                    this.___TraderOne = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader>(
                        this,
                        "TraderOne",
                        new string[] { "TraderOneId" },
                        e => global::System.Object.Equals(e.Id, this.TraderOneId),
                        () => this._TraderOne,
                        e => this._TraderOne = e);
                }
                return this.___TraderOne;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> ___TraderOne;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Contract.DetailsClass.IImplementation.TraderTwo
        {
            get
            {
                return this.TraderTwo;
            }
            set
            {
                this.TraderTwo = (global::LightSwitchApplication.Implementation.Trader)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> __TraderTwo
        {
            get
            {
                if (this.___TraderTwo == null)
                {
                    this.___TraderTwo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader>(
                        this,
                        "TraderTwo",
                        new string[] { "TraderTwoId" },
                        e => global::System.Object.Equals(e.Id, this.TraderTwoId),
                        () => this._TraderTwo,
                        e => this._TraderTwo = e);
                }
                return this.___TraderTwo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> ___TraderTwo;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Contract.DetailsClass.IImplementation.Orders
        {
            get
            {
                return this.Orders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> __Orders
        {
            get
            {
                if (this.___Orders == null)
                {
                    this.___Orders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "Orders",
                        () => this._Orders,
                        e => global::System.Object.Equals(e.ContractId, this.Id));
                }
                return this.___Orders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> ___Orders;
        
    }
    #endregion
    
    #region CreditCard
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CreditCard :
        global::LightSwitchApplication.CreditCard.DetailsClass.IImplementation
    {
        partial void OnTraderIdChanged()
        {
            this.___OnPropertyChanged("TraderId");
            this.___OnPropertyChanged("Trader");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnHolderNameChanged()
        {
            this.___OnPropertyChanged("HolderName");
        }
        
        partial void OnCardNumberChanged()
        {
            this.___OnPropertyChanged("CardNumber");
        }
        
        partial void OnExpDateChanged()
        {
            this.___OnPropertyChanged("ExpDate");
        }
        
        partial void OnSecurityCodeChanged()
        {
            this.___OnPropertyChanged("SecurityCode");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CreditCard.DetailsClass.IImplementation.Trader
        {
            get
            {
                return this.Trader;
            }
            set
            {
                this.Trader = (global::LightSwitchApplication.Implementation.Trader)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> __Trader
        {
            get
            {
                if (this.___Trader == null)
                {
                    this.___Trader = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader>(
                        this,
                        "Trader",
                        new string[] { "TraderId" },
                        e => global::System.Object.Equals(e.Id, this.TraderId),
                        () => this._Trader,
                        e => this._Trader = e);
                }
                return this.___Trader;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> ___Trader;
        
    }
    #endregion
    
    #region Group
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Group :
        global::LightSwitchApplication.Group.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Group.DetailsClass.IImplementation.Users
        {
            get
            {
                return this.Users;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.User> __Users
        {
            get
            {
                if (this.___Users == null)
                {
                    this.___Users = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.User>(
                        this,
                        "Users",
                        () => this._Users,
                        e => global::System.Object.Equals(e.GroupId, this.Id));
                }
                return this.___Users;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.User> ___Users;
        
    }
    #endregion
    
    #region Instance
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Instance :
        global::LightSwitchApplication.Instance.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnIndustryChanged()
        {
            this.___OnPropertyChanged("Industry");
        }
        
        partial void OnAdminFeePercentageChanged()
        {
            this.___OnPropertyChanged("AdminFeePercentage");
        }
        
        partial void OnPivotCurrencyIdChanged()
        {
            this.___OnPropertyChanged("PivotCurrencyId");
        }
        
        partial void OnGlobalPivotCurrencyIdChanged()
        {
            this.___OnPropertyChanged("GlobalPivotCurrencyId");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Instance.DetailsClass.IImplementation.Contracts
        {
            get
            {
                return this.Contracts;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Contract> __Contracts
        {
            get
            {
                if (this.___Contracts == null)
                {
                    this.___Contracts = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Contract>(
                        this,
                        "Contracts",
                        () => this._Contracts,
                        e => global::System.Object.Equals(e.InstanceId, this.Id));
                }
                return this.___Contracts;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Contract> ___Contracts;
        
    }
    #endregion
    
    #region Item
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Item :
        global::LightSwitchApplication.Item.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCategoryChanged()
        {
            this.___OnPropertyChanged("Category");
        }
        
        partial void OnSubCategoryChanged()
        {
            this.___OnPropertyChanged("SubCategory");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnUnitChanged()
        {
            this.___OnPropertyChanged("Unit");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnImageUrlChanged()
        {
            this.___OnPropertyChanged("ImageUrl");
        }
        
        partial void OnRatingChanged()
        {
            this.___OnPropertyChanged("Rating");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Item.DetailsClass.IImplementation.OrderLineItems
        {
            get
            {
                return this.OrderLineItems;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderLineItem> __OrderLineItems
        {
            get
            {
                if (this.___OrderLineItems == null)
                {
                    this.___OrderLineItems = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderLineItem>(
                        this,
                        "OrderLineItems",
                        () => this._OrderLineItems,
                        e => global::System.Object.Equals(e.ItemId, this.Id));
                }
                return this.___OrderLineItems;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderLineItem> ___OrderLineItems;
        
    }
    #endregion
    
    #region OrderLineItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class OrderLineItem :
        global::LightSwitchApplication.OrderLineItem.DetailsClass.IImplementation
    {
        partial void OnItemIdChanged()
        {
            this.___OnPropertyChanged("ItemId");
            this.___OnPropertyChanged("Item");
        }
        
        partial void OnOrderIdChanged()
        {
            this.___OnPropertyChanged("OrderId");
            this.___OnPropertyChanged("Order");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnFulfilmentDateChanged()
        {
            this.___OnPropertyChanged("FulfilmentDate");
        }
        
        partial void OnUnitsChanged()
        {
            this.___OnPropertyChanged("Units");
        }
        
        partial void OnPricePerUnitChanged()
        {
            this.___OnPropertyChanged("PricePerUnit");
        }
        
        partial void OnAmountChanged()
        {
            this.___OnPropertyChanged("Amount");
        }
        
        partial void OnAdminFeeChanged()
        {
            this.___OnPropertyChanged("AdminFee");
        }
        
        partial void OnPivotExchangeRateChanged()
        {
            this.___OnPropertyChanged("PivotExchangeRate");
        }
        
        partial void OnGlobalPivotExchangeRateChanged()
        {
            this.___OnPropertyChanged("GlobalPivotExchangeRate");
        }
        
        partial void OnCurrencyIdChanged()
        {
            this.___OnPropertyChanged("CurrencyId");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.OrderLineItem.DetailsClass.IImplementation.Item
        {
            get
            {
                return this.Item;
            }
            set
            {
                this.Item = (global::LightSwitchApplication.Implementation.Item)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Item> __Item
        {
            get
            {
                if (this.___Item == null)
                {
                    this.___Item = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Item>(
                        this,
                        "Item",
                        new string[] { "ItemId" },
                        e => global::System.Object.Equals(e.Id, this.ItemId),
                        () => this._Item,
                        e => this._Item = e);
                }
                return this.___Item;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Item> ___Item;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.OrderLineItem.DetailsClass.IImplementation.Order
        {
            get
            {
                return this.Order;
            }
            set
            {
                this.Order = (global::LightSwitchApplication.Implementation.Order)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Order> __Order
        {
            get
            {
                if (this.___Order == null)
                {
                    this.___Order = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "Order",
                        new string[] { "OrderId" },
                        e => global::System.Object.Equals(e.Id, this.OrderId),
                        () => this._Order,
                        e => this._Order = e);
                }
                return this.___Order;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Order> ___Order;
        
    }
    #endregion
    
    #region Order
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Order :
        global::LightSwitchApplication.Order.DetailsClass.IImplementation
    {
        partial void OnAircraftIdChanged()
        {
            this.___OnPropertyChanged("AircraftId");
            this.___OnPropertyChanged("Aircraft");
        }
        
        partial void OnLandingAirportIdChanged()
        {
            this.___OnPropertyChanged("LandingAirportId");
            this.___OnPropertyChanged("LandingAirport");
        }
        
        partial void OnTakeoffAirportIdChanged()
        {
            this.___OnPropertyChanged("TakeoffAirportId");
            this.___OnPropertyChanged("TakeoffAirport");
        }
        
        partial void OnContractIdChanged()
        {
            this.___OnPropertyChanged("ContractId");
            this.___OnPropertyChanged("Contract");
        }
        
        partial void OnBuyerIdChanged()
        {
            this.___OnPropertyChanged("BuyerId");
            this.___OnPropertyChanged("Buyer");
        }
        
        partial void OnSellerIdChanged()
        {
            this.___OnPropertyChanged("SellerId");
            this.___OnPropertyChanged("Seller");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnOrderDateChanged()
        {
            this.___OnPropertyChanged("OrderDate");
        }
        
        partial void OnQuotationDateChanged()
        {
            this.___OnPropertyChanged("QuotationDate");
        }
        
        partial void OnIsQuotedChanged()
        {
            this.___OnPropertyChanged("IsQuoted");
        }
        
        partial void OnApprovalDateChanged()
        {
            this.___OnPropertyChanged("ApprovalDate");
        }
        
        partial void OnIsApprovedChanged()
        {
            this.___OnPropertyChanged("IsApproved");
        }
        
        partial void OnFulfilmentDateChanged()
        {
            this.___OnPropertyChanged("FulfilmentDate");
        }
        
        partial void OnIsFulfilledChanged()
        {
            this.___OnPropertyChanged("IsFulfilled");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnAmountChanged()
        {
            this.___OnPropertyChanged("Amount");
        }
        
        partial void OnPivotExchangeRateChanged()
        {
            this.___OnPropertyChanged("PivotExchangeRate");
        }
        
        partial void OnGlobalPivotExchangeRateChanged()
        {
            this.___OnPropertyChanged("GlobalPivotExchangeRate");
        }
        
        partial void OnAdminFeeChanged()
        {
            this.___OnPropertyChanged("AdminFee");
        }
        
        partial void OnBuyerCardHolderNameChanged()
        {
            this.___OnPropertyChanged("BuyerCardHolderName");
        }
        
        partial void OnBuyerCardNumberChanged()
        {
            this.___OnPropertyChanged("BuyerCardNumber");
        }
        
        partial void OnBuyerCardExpDateChanged()
        {
            this.___OnPropertyChanged("BuyerCardExpDate");
        }
        
        partial void OnBuyerCardSecurityCodeChanged()
        {
            this.___OnPropertyChanged("BuyerCardSecurityCode");
        }
        
        partial void OnBuyerPaypalUserIdChanged()
        {
            this.___OnPropertyChanged("BuyerPaypalUserId");
        }
        
        partial void OnBuyerPaypalPasswordChanged()
        {
            this.___OnPropertyChanged("BuyerPaypalPassword");
        }
        
        partial void OnBuyerReferenceNumberChanged()
        {
            this.___OnPropertyChanged("BuyerReferenceNumber");
        }
        
        partial void OnSellerCardHolderNameChanged()
        {
            this.___OnPropertyChanged("SellerCardHolderName");
        }
        
        partial void OnSellerCardNumberChanged()
        {
            this.___OnPropertyChanged("SellerCardNumber");
        }
        
        partial void OnSellerCardExpDateChanged()
        {
            this.___OnPropertyChanged("SellerCardExpDate");
        }
        
        partial void OnSellerCardSecurityCodeChanged()
        {
            this.___OnPropertyChanged("SellerCardSecurityCode");
        }
        
        partial void OnSellerPaypalUserIdChanged()
        {
            this.___OnPropertyChanged("SellerPaypalUserId");
        }
        
        partial void OnSellerPaypalPasswordChanged()
        {
            this.___OnPropertyChanged("SellerPaypalPassword");
        }
        
        partial void OnSellerReferenceNumberChanged()
        {
            this.___OnPropertyChanged("SellerReferenceNumber");
        }
        
        partial void OnOperateurChanged()
        {
            this.___OnPropertyChanged("Operateur");
        }
        
        partial void OnFlightNumberChanged()
        {
            this.___OnPropertyChanged("FlightNumber");
        }
        
        partial void OnEstimatedTakeoffTimeChanged()
        {
            this.___OnPropertyChanged("EstimatedTakeoffTime");
        }
        
        partial void OnEstimatedLandingTimeChanged()
        {
            this.___OnPropertyChanged("EstimatedLandingTime");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Order.DetailsClass.IImplementation.OrderLineItems
        {
            get
            {
                return this.OrderLineItems;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderLineItem> __OrderLineItems
        {
            get
            {
                if (this.___OrderLineItems == null)
                {
                    this.___OrderLineItems = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderLineItem>(
                        this,
                        "OrderLineItems",
                        () => this._OrderLineItems,
                        e => global::System.Object.Equals(e.OrderId, this.Id));
                }
                return this.___OrderLineItems;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.OrderLineItem> ___OrderLineItems;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Aircraft
        {
            get
            {
                return this.Aircraft;
            }
            set
            {
                this.Aircraft = (global::LightSwitchApplication.Implementation.Aircraft)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Aircraft> __Aircraft
        {
            get
            {
                if (this.___Aircraft == null)
                {
                    this.___Aircraft = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Aircraft>(
                        this,
                        "Aircraft",
                        new string[] { "AircraftId" },
                        e => global::System.Object.Equals(e.Id, this.AircraftId),
                        () => this._Aircraft,
                        e => this._Aircraft = e);
                }
                return this.___Aircraft;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Aircraft> ___Aircraft;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.LandingAirport
        {
            get
            {
                return this.LandingAirport;
            }
            set
            {
                this.LandingAirport = (global::LightSwitchApplication.Implementation.Airport)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Airport> __LandingAirport
        {
            get
            {
                if (this.___LandingAirport == null)
                {
                    this.___LandingAirport = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Airport>(
                        this,
                        "LandingAirport",
                        new string[] { "LandingAirportId" },
                        e => global::System.Object.Equals(e.Id, this.LandingAirportId),
                        () => this._LandingAirport,
                        e => this._LandingAirport = e);
                }
                return this.___LandingAirport;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Airport> ___LandingAirport;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.TakeoffAirport
        {
            get
            {
                return this.TakeoffAirport;
            }
            set
            {
                this.TakeoffAirport = (global::LightSwitchApplication.Implementation.Airport)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Airport> __TakeoffAirport
        {
            get
            {
                if (this.___TakeoffAirport == null)
                {
                    this.___TakeoffAirport = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Airport>(
                        this,
                        "TakeoffAirport",
                        new string[] { "TakeoffAirportId" },
                        e => global::System.Object.Equals(e.Id, this.TakeoffAirportId),
                        () => this._TakeoffAirport,
                        e => this._TakeoffAirport = e);
                }
                return this.___TakeoffAirport;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Airport> ___TakeoffAirport;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Contract
        {
            get
            {
                return this.Contract;
            }
            set
            {
                this.Contract = (global::LightSwitchApplication.Implementation.Contract)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Contract> __Contract
        {
            get
            {
                if (this.___Contract == null)
                {
                    this.___Contract = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Contract>(
                        this,
                        "Contract",
                        new string[] { "ContractId" },
                        e => global::System.Object.Equals(e.Id, this.ContractId),
                        () => this._Contract,
                        e => this._Contract = e);
                }
                return this.___Contract;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Contract> ___Contract;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Buyer
        {
            get
            {
                return this.Buyer;
            }
            set
            {
                this.Buyer = (global::LightSwitchApplication.Implementation.Trader)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> __Buyer
        {
            get
            {
                if (this.___Buyer == null)
                {
                    this.___Buyer = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader>(
                        this,
                        "Buyer",
                        new string[] { "BuyerId" },
                        e => global::System.Object.Equals(e.Id, this.BuyerId),
                        () => this._Buyer,
                        e => this._Buyer = e);
                }
                return this.___Buyer;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> ___Buyer;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Seller
        {
            get
            {
                return this.Seller;
            }
            set
            {
                this.Seller = (global::LightSwitchApplication.Implementation.Trader)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> __Seller
        {
            get
            {
                if (this.___Seller == null)
                {
                    this.___Seller = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader>(
                        this,
                        "Seller",
                        new string[] { "SellerId" },
                        e => global::System.Object.Equals(e.Id, this.SellerId),
                        () => this._Seller,
                        e => this._Seller = e);
                }
                return this.___Seller;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> ___Seller;
        
    }
    #endregion
    
    #region Trader
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Trader :
        global::LightSwitchApplication.Trader.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnAccountChanged()
        {
            this.___OnPropertyChanged("Account");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnAddressChanged()
        {
            this.___OnPropertyChanged("Address");
        }
        
        partial void OnAddress2Changed()
        {
            this.___OnPropertyChanged("Address2");
        }
        
        partial void OnCityChanged()
        {
            this.___OnPropertyChanged("City");
        }
        
        partial void OnPhoneChanged()
        {
            this.___OnPropertyChanged("Phone");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnContactChanged()
        {
            this.___OnPropertyChanged("Contact");
        }
        
        partial void OnFaxChanged()
        {
            this.___OnPropertyChanged("Fax");
        }
        
        partial void OnCurrentInvoiceCounterChanged()
        {
            this.___OnPropertyChanged("CurrentInvoiceCounter");
        }
        
        partial void OnCountryIdChanged()
        {
            this.___OnPropertyChanged("CountryId");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.TraderOneContracts
        {
            get
            {
                return this.TraderOneContracts;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Contract> __TraderOneContracts
        {
            get
            {
                if (this.___TraderOneContracts == null)
                {
                    this.___TraderOneContracts = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Contract>(
                        this,
                        "TraderOneContracts",
                        () => this._TraderOneContracts,
                        e => global::System.Object.Equals(e.TraderOneId, this.Id));
                }
                return this.___TraderOneContracts;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Contract> ___TraderOneContracts;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.TraderTwoContracts
        {
            get
            {
                return this.TraderTwoContracts;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Contract> __TraderTwoContracts
        {
            get
            {
                if (this.___TraderTwoContracts == null)
                {
                    this.___TraderTwoContracts = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Contract>(
                        this,
                        "TraderTwoContracts",
                        () => this._TraderTwoContracts,
                        e => global::System.Object.Equals(e.TraderTwoId, this.Id));
                }
                return this.___TraderTwoContracts;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Contract> ___TraderTwoContracts;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.CreditCards
        {
            get
            {
                return this.CreditCards;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CreditCard> __CreditCards
        {
            get
            {
                if (this.___CreditCards == null)
                {
                    this.___CreditCards = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CreditCard>(
                        this,
                        "CreditCards",
                        () => this._CreditCards,
                        e => global::System.Object.Equals(e.TraderId, this.Id));
                }
                return this.___CreditCards;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CreditCard> ___CreditCards;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.BuyerOrders
        {
            get
            {
                return this.BuyerOrders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> __BuyerOrders
        {
            get
            {
                if (this.___BuyerOrders == null)
                {
                    this.___BuyerOrders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "BuyerOrders",
                        () => this._BuyerOrders,
                        e => global::System.Object.Equals(e.BuyerId, this.Id));
                }
                return this.___BuyerOrders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> ___BuyerOrders;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.TraderOrders
        {
            get
            {
                return this.TraderOrders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> __TraderOrders
        {
            get
            {
                if (this.___TraderOrders == null)
                {
                    this.___TraderOrders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order>(
                        this,
                        "TraderOrders",
                        () => this._TraderOrders,
                        e => global::System.Object.Equals(e.SellerId, this.Id));
                }
                return this.___TraderOrders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Order> ___TraderOrders;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.TraderRegistrationTokens
        {
            get
            {
                return this.TraderRegistrationTokens;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TraderRegistrationToken> __TraderRegistrationTokens
        {
            get
            {
                if (this.___TraderRegistrationTokens == null)
                {
                    this.___TraderRegistrationTokens = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TraderRegistrationToken>(
                        this,
                        "TraderRegistrationTokens",
                        () => this._TraderRegistrationTokens,
                        e => global::System.Object.Equals(e.TraderId, this.Id));
                }
                return this.___TraderRegistrationTokens;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TraderRegistrationToken> ___TraderRegistrationTokens;
        
    }
    #endregion
    
    #region User
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class User :
        global::LightSwitchApplication.User.DetailsClass.IImplementation
    {
        partial void OnGroupIdChanged()
        {
            this.___OnPropertyChanged("GroupId");
            this.___OnPropertyChanged("Group");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnLoginChanged()
        {
            this.___OnPropertyChanged("Login");
        }
        
        partial void OnPasswordChanged()
        {
            this.___OnPropertyChanged("Password");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnPhotoUrlChanged()
        {
            this.___OnPropertyChanged("PhotoUrl");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.User.DetailsClass.IImplementation.Group
        {
            get
            {
                return this.Group;
            }
            set
            {
                this.Group = (global::LightSwitchApplication.Implementation.Group)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Group> __Group
        {
            get
            {
                if (this.___Group == null)
                {
                    this.___Group = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Group>(
                        this,
                        "Group",
                        new string[] { "GroupId" },
                        e => global::System.Object.Equals(e.Id, this.GroupId),
                        () => this._Group,
                        e => this._Group = e);
                }
                return this.___Group;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Group> ___Group;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.User.DetailsClass.IImplementation.UserConfigurationItems
        {
            get
            {
                return this.UserConfigurationItems;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.UserConfigurationItem> __UserConfigurationItems
        {
            get
            {
                if (this.___UserConfigurationItems == null)
                {
                    this.___UserConfigurationItems = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.UserConfigurationItem>(
                        this,
                        "UserConfigurationItems",
                        () => this._UserConfigurationItems,
                        e => global::System.Object.Equals(e.UserId, this.Id));
                }
                return this.___UserConfigurationItems;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.UserConfigurationItem> ___UserConfigurationItems;
        
    }
    #endregion
    
    #region TraderRegistrationToken
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TraderRegistrationToken :
        global::LightSwitchApplication.TraderRegistrationToken.DetailsClass.IImplementation
    {
        partial void OnTraderIdChanged()
        {
            this.___OnPropertyChanged("TraderId");
            this.___OnPropertyChanged("Trader");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreateDateChanged()
        {
            this.___OnPropertyChanged("CreateDate");
        }
        
        partial void OnTokenChanged()
        {
            this.___OnPropertyChanged("Token");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TraderRegistrationToken.DetailsClass.IImplementation.Trader
        {
            get
            {
                return this.Trader;
            }
            set
            {
                this.Trader = (global::LightSwitchApplication.Implementation.Trader)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> __Trader
        {
            get
            {
                if (this.___Trader == null)
                {
                    this.___Trader = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader>(
                        this,
                        "Trader",
                        new string[] { "TraderId" },
                        e => global::System.Object.Equals(e.Id, this.TraderId),
                        () => this._Trader,
                        e => this._Trader = e);
                }
                return this.___Trader;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Trader> ___Trader;
        
    }
    #endregion
    
    #region UserConfigurationItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AviTradeOLTPData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class UserConfigurationItem :
        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.IImplementation
    {
        partial void OnUserIdChanged()
        {
            this.___OnPropertyChanged("UserId");
            this.___OnPropertyChanged("User");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnKeyChanged()
        {
            this.___OnPropertyChanged("Key");
        }
        
        partial void OnValueChanged()
        {
            this.___OnPropertyChanged("Value");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.UserConfigurationItem.DetailsClass.IImplementation.User
        {
            get
            {
                return this.User;
            }
            set
            {
                this.User = (global::LightSwitchApplication.Implementation.User)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.User> __User
        {
            get
            {
                if (this.___User == null)
                {
                    this.___User = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.User>(
                        this,
                        "User",
                        new string[] { "UserId" },
                        e => global::System.Object.Equals(e.Id, this.UserId),
                        () => this._User,
                        e => this._User = e);
                }
                return this.___User;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.User> ___User;
        
    }
    #endregion
    
    #region AviTradeOLTPDataObjectContext
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AviTradeOLTPDataObjectContext
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Aircraft))
            {
                return new global::LightSwitchApplication.Implementation.Aircraft();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Airport))
            {
                return new global::LightSwitchApplication.Implementation.Airport();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Contract))
            {
                return new global::LightSwitchApplication.Implementation.Contract();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CreditCard))
            {
                return new global::LightSwitchApplication.Implementation.CreditCard();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Group))
            {
                return new global::LightSwitchApplication.Implementation.Group();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Instance))
            {
                return new global::LightSwitchApplication.Implementation.Instance();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Item))
            {
                return new global::LightSwitchApplication.Implementation.Item();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.OrderLineItem))
            {
                return new global::LightSwitchApplication.Implementation.OrderLineItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Order))
            {
                return new global::LightSwitchApplication.Implementation.Order();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Trader))
            {
                return new global::LightSwitchApplication.Implementation.Trader();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.User))
            {
                return new global::LightSwitchApplication.Implementation.User();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TraderRegistrationToken))
            {
                return new global::LightSwitchApplication.Implementation.TraderRegistrationToken();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.UserConfigurationItem))
            {
                return new global::LightSwitchApplication.Implementation.UserConfigurationItem();
            }
            return null;
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.AviTradeOLTPData))
            {
                return new global::LightSwitchApplication.AviTradeOLTPData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.AviTradeOLTPData))
            {
                return new global::LightSwitchApplication.Implementation.AviTradeOLTPDataObjectContext(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../AviTradeOLTPData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Aircraft) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Aircraft);
            }
            if (typeof(global::LightSwitchApplication.Airport) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Airport);
            }
            if (typeof(global::LightSwitchApplication.Contract) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Contract);
            }
            if (typeof(global::LightSwitchApplication.CreditCard) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CreditCard);
            }
            if (typeof(global::LightSwitchApplication.Group) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Group);
            }
            if (typeof(global::LightSwitchApplication.Instance) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Instance);
            }
            if (typeof(global::LightSwitchApplication.Item) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Item);
            }
            if (typeof(global::LightSwitchApplication.OrderLineItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.OrderLineItem);
            }
            if (typeof(global::LightSwitchApplication.Order) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Order);
            }
            if (typeof(global::LightSwitchApplication.Trader) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Trader);
            }
            if (typeof(global::LightSwitchApplication.User) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.User);
            }
            if (typeof(global::LightSwitchApplication.TraderRegistrationToken) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TraderRegistrationToken);
            }
            if (typeof(global::LightSwitchApplication.UserConfigurationItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.UserConfigurationItem);
            }
            return null;
        }
    }
}
