//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class AviTradeOLTPDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::AviTradeOLTPData.Implementation.AviTradeOLTPDataObjectContext>
    {
    
        public AviTradeOLTPDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService()
        {
            return new global::LightSwitchApplication.DataWorkspace().AviTradeOLTPData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class AviTradeOLTPDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::AviTradeOLTPData.Implementation.AviTradeOLTPDataObjectContext>
    {
        public AviTradeOLTPDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.User> UserByLoginCredentials(string UserId, string Password)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.User> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::AviTradeOLTPData.Implementation.User>("Users"),
                (u) => ((u.Login.CompareTo(UserId) == 0) && (u.Password.CompareTo(Password) == 0)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.User> UserByLoginName(string Login)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.User> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::AviTradeOLTPData.Implementation.User>("Users"),
                (u) => (u.Login.CompareTo(Login) == 0));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Order> WaitingToBeQuotedOrdersByTrader(string TraderAccount)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Order> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::AviTradeOLTPData.Implementation.Order>("Orders"),
                    (o) => ((o.Status == 0) && (o.Seller.Account.CompareTo(TraderAccount) == 0))),
                (o) => o.OrderDate);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.TraderRegistrationToken> TraderByToken(string Token)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.TraderRegistrationToken> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::AviTradeOLTPData.Implementation.TraderRegistrationToken>("TraderRegistrationTokens"),
                (t) => (t.Token.CompareTo(Token) == 0));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.UserConfigurationItem> TraderCodeByUser(global::System.Nullable<int> UserId)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.UserConfigurationItem> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::AviTradeOLTPData.Implementation.UserConfigurationItem>("UserConfigurationItems"),
                (u) => ((UserId.HasValue && (u.User.Id == UserId)) && (u.Key.CompareTo("TraderCode") == 0)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Order> SubmittedOrdersByTrader(string TraderAccount)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Order> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::AviTradeOLTPData.Implementation.Order>("Orders"),
                    (o) => ((o.Status == 0) && (o.Buyer.Account.CompareTo(TraderAccount) == 0))),
                (o) => o.OrderDate);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Order> ApprovedOrdersByTrader(string TraderAccount)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Order> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::AviTradeOLTPData.Implementation.Order>("Orders"),
                    (o) => (((o.Status == 2) && (o.Buyer.Account.CompareTo(TraderAccount) == 0)) || (o.Seller.Account.CompareTo(TraderAccount) == 0))),
                (o) => o.ApprovalDate);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Contract> ContractsByTrader(string TraderAccount)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Contract> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::AviTradeOLTPData.Implementation.Contract>("Contracts"),
                    (c) => ((c.TraderOne.Account.CompareTo(TraderAccount) == 0) || (c.TraderTwo.Account.CompareTo(TraderAccount) == 0))),
                (c) => c.EndDate);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Order> OrdersByAdvancedSearch(global::System.Nullable<global::System.DateTime> FromDate, global::System.Nullable<global::System.DateTime> ToDate, string BuyerName, string SellerName, global::System.Nullable<int> Status)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Order> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::AviTradeOLTPData.Implementation.Order>("Orders"),
                    (o) => (((((FromDate.HasValue && (o.OrderDate >= FromDate)) && (ToDate.HasValue && (o.OrderDate <= ToDate))) && (o.Buyer.Name.CompareTo(BuyerName) == 0)) && (o.Seller.Name.CompareTo(SellerName) == 0)) && (Status.HasValue && (o.Status == Status)))),
                (o) => o.OrderDate);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Trader> AllTraders(string LoggedInTrader)
        {
            global::System.Linq.IQueryable<global::AviTradeOLTPData.Implementation.Trader> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::AviTradeOLTPData.Implementation.Trader>("Traders"),
                (t) => ((t.Name.CompareTo(LoggedInTrader) == 0) == false));
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::AviTradeOLTPData.Implementation.Aircraft))
            {
                return new global::AviTradeOLTPData.Implementation.Aircraft();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.Airport))
            {
                return new global::AviTradeOLTPData.Implementation.Airport();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.Contract))
            {
                return new global::AviTradeOLTPData.Implementation.Contract();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.CreditCard))
            {
                return new global::AviTradeOLTPData.Implementation.CreditCard();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.Group))
            {
                return new global::AviTradeOLTPData.Implementation.Group();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.Instance))
            {
                return new global::AviTradeOLTPData.Implementation.Instance();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.Item))
            {
                return new global::AviTradeOLTPData.Implementation.Item();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.OrderLineItem))
            {
                return new global::AviTradeOLTPData.Implementation.OrderLineItem();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.Order))
            {
                return new global::AviTradeOLTPData.Implementation.Order();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.Trader))
            {
                return new global::AviTradeOLTPData.Implementation.Trader();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.User))
            {
                return new global::AviTradeOLTPData.Implementation.User();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.TraderRegistrationToken))
            {
                return new global::AviTradeOLTPData.Implementation.TraderRegistrationToken();
            }
            if (type == typeof(global::AviTradeOLTPData.Implementation.UserConfigurationItem))
            {
                return new global::AviTradeOLTPData.Implementation.UserConfigurationItem();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::AviTradeOLTPData.Implementation.AviTradeOLTPDataObjectContext CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::AviTradeOLTPData.Implementation.AviTradeOLTPDataObjectContext(base.GetEntityConnectionString(
                "AviTradeOLTPData", 
                "res://" + assemblyName + "/AviTradeOLTPData.csdl|res://" + assemblyName + "/AviTradeOLTPData.ssdl|res://" + assemblyName + "/AviTradeOLTPData.msl", 
                "System.Data.SqlClient"));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Aircraft))
            {
                return new global::AviTradeOLTPData.Implementation.Aircraft();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Airport))
            {
                return new global::AviTradeOLTPData.Implementation.Airport();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Contract))
            {
                return new global::AviTradeOLTPData.Implementation.Contract();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CreditCard))
            {
                return new global::AviTradeOLTPData.Implementation.CreditCard();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Group))
            {
                return new global::AviTradeOLTPData.Implementation.Group();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Instance))
            {
                return new global::AviTradeOLTPData.Implementation.Instance();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Item))
            {
                return new global::AviTradeOLTPData.Implementation.Item();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.OrderLineItem))
            {
                return new global::AviTradeOLTPData.Implementation.OrderLineItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Order))
            {
                return new global::AviTradeOLTPData.Implementation.Order();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Trader))
            {
                return new global::AviTradeOLTPData.Implementation.Trader();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.User))
            {
                return new global::AviTradeOLTPData.Implementation.User();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TraderRegistrationToken))
            {
                return new global::AviTradeOLTPData.Implementation.TraderRegistrationToken();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.UserConfigurationItem))
            {
                return new global::AviTradeOLTPData.Implementation.UserConfigurationItem();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.AviTradeOLTPData))
            {
                return new global::LightSwitchApplication.AviTradeOLTPDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.AviTradeOLTPData))
            {
                return new global::LightSwitchApplication.Implementation.AviTradeOLTPDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Aircraft) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.Aircraft);
            }
            if (typeof(global::LightSwitchApplication.Airport) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.Airport);
            }
            if (typeof(global::LightSwitchApplication.Contract) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.Contract);
            }
            if (typeof(global::LightSwitchApplication.CreditCard) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.CreditCard);
            }
            if (typeof(global::LightSwitchApplication.Group) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.Group);
            }
            if (typeof(global::LightSwitchApplication.Instance) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.Instance);
            }
            if (typeof(global::LightSwitchApplication.Item) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.Item);
            }
            if (typeof(global::LightSwitchApplication.OrderLineItem) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.OrderLineItem);
            }
            if (typeof(global::LightSwitchApplication.Order) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.Order);
            }
            if (typeof(global::LightSwitchApplication.Trader) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.Trader);
            }
            if (typeof(global::LightSwitchApplication.User) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.User);
            }
            if (typeof(global::LightSwitchApplication.TraderRegistrationToken) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.TraderRegistrationToken);
            }
            if (typeof(global::LightSwitchApplication.UserConfigurationItem) == definitionType)
            {
                return typeof(global::AviTradeOLTPData.Implementation.UserConfigurationItem);
            }
            return null;
        }
    }
}

namespace AviTradeOLTPData.Implementation
{

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Aircraft :
        global::LightSwitchApplication.Aircraft.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Aircraft.DetailsClass.IImplementation.Orders
        {
            get
            {
                return this.Orders;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Airport :
        global::LightSwitchApplication.Airport.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Airport.DetailsClass.IImplementation.Orders
        {
            get
            {
                return this.Orders;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Airport.DetailsClass.IImplementation.Orders1
        {
            get
            {
                return this.Orders1;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Contract :
        global::LightSwitchApplication.Contract.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Contract.DetailsClass.IImplementation.Instance
        {
            get
            {
                return this.Instance;
            }
            set
            {
                this.Instance = (global::AviTradeOLTPData.Implementation.Instance)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Instance");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Contract.DetailsClass.IImplementation.TraderOne
        {
            get
            {
                return this.TraderOne;
            }
            set
            {
                this.TraderOne = (global::AviTradeOLTPData.Implementation.Trader)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TraderOne");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Contract.DetailsClass.IImplementation.TraderTwo
        {
            get
            {
                return this.TraderTwo;
            }
            set
            {
                this.TraderTwo = (global::AviTradeOLTPData.Implementation.Trader)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TraderTwo");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Contract.DetailsClass.IImplementation.Orders
        {
            get
            {
                return this.Orders;
            }
        }
        
        partial void OnInstanceIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Instance");
            }
        }
        
        partial void OnTraderOneIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TraderOne");
            }
        }
        
        partial void OnTraderTwoIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TraderTwo");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CreditCard :
        global::LightSwitchApplication.CreditCard.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CreditCard.DetailsClass.IImplementation.Trader
        {
            get
            {
                return this.Trader;
            }
            set
            {
                this.Trader = (global::AviTradeOLTPData.Implementation.Trader)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Trader");
                }
            }
        }
        
        partial void OnTraderIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Trader");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Group :
        global::LightSwitchApplication.Group.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Group.DetailsClass.IImplementation.Users
        {
            get
            {
                return this.Users;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Instance :
        global::LightSwitchApplication.Instance.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Instance.DetailsClass.IImplementation.Contracts
        {
            get
            {
                return this.Contracts;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Item :
        global::LightSwitchApplication.Item.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Item.DetailsClass.IImplementation.OrderLineItems
        {
            get
            {
                return this.OrderLineItems;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class OrderLineItem :
        global::LightSwitchApplication.OrderLineItem.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.OrderLineItem.DetailsClass.IImplementation.Item
        {
            get
            {
                return this.Item;
            }
            set
            {
                this.Item = (global::AviTradeOLTPData.Implementation.Item)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Item");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.OrderLineItem.DetailsClass.IImplementation.Order
        {
            get
            {
                return this.Order;
            }
            set
            {
                this.Order = (global::AviTradeOLTPData.Implementation.Order)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Order");
                }
            }
        }
        
        partial void OnItemIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Item");
            }
        }
        
        partial void OnOrderIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Order");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Order :
        global::LightSwitchApplication.Order.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Order.DetailsClass.IImplementation.OrderLineItems
        {
            get
            {
                return this.OrderLineItems;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Aircraft
        {
            get
            {
                return this.Aircraft;
            }
            set
            {
                this.Aircraft = (global::AviTradeOLTPData.Implementation.Aircraft)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Aircraft");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.LandingAirport
        {
            get
            {
                return this.LandingAirport;
            }
            set
            {
                this.LandingAirport = (global::AviTradeOLTPData.Implementation.Airport)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("LandingAirport");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.TakeoffAirport
        {
            get
            {
                return this.TakeoffAirport;
            }
            set
            {
                this.TakeoffAirport = (global::AviTradeOLTPData.Implementation.Airport)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TakeoffAirport");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Contract
        {
            get
            {
                return this.Contract;
            }
            set
            {
                this.Contract = (global::AviTradeOLTPData.Implementation.Contract)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Contract");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Buyer
        {
            get
            {
                return this.Buyer;
            }
            set
            {
                this.Buyer = (global::AviTradeOLTPData.Implementation.Trader)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Buyer");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Order.DetailsClass.IImplementation.Seller
        {
            get
            {
                return this.Seller;
            }
            set
            {
                this.Seller = (global::AviTradeOLTPData.Implementation.Trader)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Seller");
                }
            }
        }
        
        partial void OnAircraftIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Aircraft");
            }
        }
        
        partial void OnLandingAirportIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("LandingAirport");
            }
        }
        
        partial void OnTakeoffAirportIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TakeoffAirport");
            }
        }
        
        partial void OnContractIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Contract");
            }
        }
        
        partial void OnBuyerIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Buyer");
            }
        }
        
        partial void OnSellerIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Seller");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Trader :
        global::LightSwitchApplication.Trader.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.TraderOneContracts
        {
            get
            {
                return this.TraderOneContracts;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.TraderTwoContracts
        {
            get
            {
                return this.TraderTwoContracts;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.CreditCards
        {
            get
            {
                return this.CreditCards;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.BuyerOrders
        {
            get
            {
                return this.BuyerOrders;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.TraderOrders
        {
            get
            {
                return this.TraderOrders;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Trader.DetailsClass.IImplementation.TraderRegistrationTokens
        {
            get
            {
                return this.TraderRegistrationTokens;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class User :
        global::LightSwitchApplication.User.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.User.DetailsClass.IImplementation.Group
        {
            get
            {
                return this.Group;
            }
            set
            {
                this.Group = (global::AviTradeOLTPData.Implementation.Group)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Group");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.User.DetailsClass.IImplementation.UserConfigurationItems
        {
            get
            {
                return this.UserConfigurationItems;
            }
        }
        
        partial void OnGroupIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Group");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TraderRegistrationToken :
        global::LightSwitchApplication.TraderRegistrationToken.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TraderRegistrationToken.DetailsClass.IImplementation.Trader
        {
            get
            {
                return this.Trader;
            }
            set
            {
                this.Trader = (global::AviTradeOLTPData.Implementation.Trader)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Trader");
                }
            }
        }
        
        partial void OnTraderIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Trader");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class UserConfigurationItem :
        global::LightSwitchApplication.UserConfigurationItem.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.UserConfigurationItem.DetailsClass.IImplementation.User
        {
            get
            {
                return this.User;
            }
            set
            {
                this.User = (global::AviTradeOLTPData.Implementation.User)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("User");
                }
            }
        }
        
        partial void OnUserIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("User");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

